apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-node
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-node
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets", "nodes", "namespaces", "events", "persistentvolumes", "persistentvolumeclaims", "persistentvolumeclaims/status"]
    verbs: ["get", "list", "create", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments", "volumeattachments/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-node
subjects:
  - kind: ServiceAccount
    name: csi-node
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: csi-node
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-provisioner-volumeattachment-status-binding
subjects:
  - kind: ServiceAccount
    name: csi-provisioner
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: csi-provisioner
  apiGroup: rbac.authorization.k8s.io
