apiVersion: v1
kind: Secret
metadata:
  name: com.hammerspace.csi.credentials
  namespace: kube-system
type: Opaque
# This Secret provides the CSI driver's Hammerspace management/API (REST) credentials.
# It is not used as an NFS mount credential.
data:
  username: YWRtaW4=
  password: YWRtaW4=
stringData:
  endpoint: "https://anvil.example.com"
