apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-env-config
  namespace: {{ .Values.namespace | default "kube-system" }}
data:
  MOUNT_CHECK_TIMEOUT: "{{ .Values.env.MOUNT_CHECK_TIMEOUT }}"
  UNMOUNT_RETRY_COUNT: "{{ .Values.env.UNMOUNT_RETRY_COUNT }}"
  UNMOUNT_RETRY_INTERVAL: "{{ .Values.env.UNMOUNT_RETRY_INTERVAL }}"