apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: com.hammerspace.csi
spec:
  podInfoOnMount: true
  requiresRepublish: true
  volumeLifecycleModes:
    - Persistent
  storageCapacity: true