kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-restored
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: hs-storage-block
  selector:
    matchLabels:
      name: restored-block-pv
